using Microsoft.Dafny;
using Expression = Microsoft.Dafny.Expression;

namespace MutDafny.Mutator;

public class BinaryOpMutator(string op, ErrorReporter reporter) : Mutator
{
    public override void Mutate(Statement statement) { }

    public override void Mutate(Expression expression) {
        if (expression is not BinaryExpr bExpr) return;
        bExpr.Op = (BinaryExpr.Opcode)Enum.Parse(typeof(BinaryExpr.Opcode), op);
        
        var binaryExprToken = new AutoGeneratedOrigin(bExpr.Center);
        reporter.Info(MessageSource.Rewriter, binaryExprToken, $"Operation mutated to {op}");
    }

    public void MutateParent(Expression expression, ChainingExpression cExpr) {
        if (expression is not BinaryExpr bExpr) return;
        foreach (var (e, i) in cExpr.Operands.Select((e, i) => (e, i))) {
            if (e.Center.pos != bExpr.E0.Center.pos) continue;
            // if the lhs operand is at position i of the operands list
            // then the operator is at position i of the operators list
            cExpr.Operators[i] = (BinaryExpr.Opcode)Enum.Parse(typeof(BinaryExpr.Opcode), op);
            
            var binaryExprToken = new AutoGeneratedOrigin(e.Center);
            reporter.Info(MessageSource.Rewriter, binaryExprToken, $"Operation mutated to {op}");
        }
    }
}