using Microsoft.Dafny;
using Expression = Microsoft.Dafny.Expression;

namespace MutDafny.Mutator;

public class BinaryOpMutator(string op, ErrorReporter reporter) : Mutator
{
    public override void Mutate(Statement statement) { }

    public override void Mutate(Expression expression)
    {
        if (expression is not BinaryExpr bExpr) return;
        bExpr.Op = (BinaryExpr.Opcode)Enum.Parse(typeof(BinaryExpr.Opcode), op);
        
        var binaryExprToken = new AutoGeneratedOrigin(bExpr.Center);
        reporter.Info(MessageSource.Rewriter, binaryExprToken, $"Operation mutated to {op}");
    }
}