using Microsoft.Dafny;
using Microsoft.Dafny.Plugins;
using PluginConfiguration = Microsoft.Dafny.LanguageServer.Plugins.PluginConfiguration;

namespace MutDafny;

public class MutDafny : PluginConfiguration
{
    public override Rewriter[] GetRewriters(ErrorReporter reporter)
    {
        return [new Mutator(reporter)];
    }
}

file sealed class Mutator(ErrorReporter reporter) : Rewriter(reporter)
{
    public override void PreResolve(ModuleDefinition module)
    {
        // TODO: for testing, remove
        foreach (var m in module.DefaultClass.Members) {
            if (m is MethodOrFunction mf) {
                Reporter.Info(MessageSource.Rewriter, new AutoGeneratedOrigin(mf.Origin), "Plugin is working");
            }
        }
    }
}